data_ingestion:
  test_size: 0.2
  
  
model_building:
  ngram_range: [1, 3]  
  max_features: 10000
  learning_rate: 0.08
  max_depth: 20
  n_estimators: 367

AWS_TRACKING_URI: 
  experiment_URI: "http://ec2-34-204-176-204.compute-1.amazonaws.com:5000"